### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by makeusabrew** [makeusabrew/bootbox#136]
- [x] add note about no more API altering PRs being accepted until codebase is entirely refactored
- [x] ensure note is obvious in both readme and contributing file
- [x] offer some sort of WIP gist / wiki draft about the revised API direction to at least give people a heads up or an opportunity to help.
