### ISSUE TITLE
Bootbox 4.0.0 (Bootstrap 3 support) task list

### ISSUE THREAD

**Issue by makeusabrew** [makeusabrew/bootbox#139]
A miscellaneous list of tasks / features / random notes which need doing for the first 4.0.0 release.

**22/08/13: Bootbox 4.0.0 is nearly ready! Please check out the master branch to follow its progress and provide any feedback in this issue. See [this gist](https://gist.github.com/makeusabrew/6223814) for example usage.**

**core**
- [x] rewrite `alert`
- [x] rewrite `confirm`
- [x] rewrite `prompt`
- [x] rewrite `dialog`
- [x] add customised .jshintrc
- [x] reimplement locale handling
- [x] add `setDefaults` method instead of several setX / animate() methods
- [x] allow optional extra class on dialog wrapper (#116)
- [x] add close buttons to basic dialogs (#92)
- [x] allow dialog titles to be specified (#51, #112)
- [x] fix `backdrop: true` not firing close handler (#77) [dropped: true should not be a supported value]
- [x] investigate viability of #123 - add bootbox specific class to backdrops [see ticket details]
- [x] reimplement button class support
- [x] reimplement support for animate on/off
- [x] investigate on shown event not firing in IE 7-8-9 (#85)
- [x] investigate possibility of adding close button without a header - padding is massive
- [x] create `createButtons` helper, change label method to `createLabels`, remove defaults where not needed (e.g. alert)
- [x] make prompt input full width
- [x] revisit all notes in v3.3.0 release and check they are catered for
- [x] revisit class vs className
- [x] eliminate document param, make jQuery injectable into init

**docs**
- [ ] add FAQs; even if it only has one (async Vs sync)
- [x] overhaul for Bootstrap 3 support
- [x] update all examples according to v4 API
- [x] ensure all options ( / defaults) are covered
- [ ] add quick migration guide from v3.x to v4.x

**tests**
- [x] rewrite alert tests
- [x] rewrite confirm tests
- [x] rewrite prompt tests
- [x] rewrite basic tests
- [x] add code coverage metrics to CI
- [x] upgrade to karma 0.10.x
- [x] rewrite dialog tests
- [x] write setDefaults tests
- [x] rewrite locale tests

Things looking likely to get bumped until 4.1.0:
- [ ] reimplement icon support
- [ ] add left/right arrow support for button focus (#137)
- [ ] create bower package (#117)
- [ ] detect if icons/classes start with a dot; take as full class if so, otherwise assume bootstrap prefixes (not convinced about this)
- [ ] implement prompt input types (#135, #140)
- [ ] add `placeholder` support to prompt
- [ ] allow setDefaults to take two params for single key/val setting
- [ ] set default locale based on html lang attribute
- [ ] allow user to specify which button has focus in options argument
