### ISSUE TITLE
Bootstrap 4.1.0 (next minor release) task list

### ISSUE THREAD

**Issue by makeusabrew** [makeusabrew/bootbox#142]
A miscellaneous list of tasks / features / random notes which need doing for the first minor v4 release; v4.1.0.

**core**
- [x] create bower package (#117)
- [x] implement prompt input types (#135, #140)
- [x] add `placeholder` support to prompt
- [x] allow setDefaults to take two params for single key/val setting
- [x] add different classes for alert, confirm and prompt dialogs (#159)

**internal**
- [x] remove old v3.x tests folder
- [x] ensure bootstrap test dependency is 3.0.0 stable (not WIP)
- [x] look at build variations: bootbox.min.js & jquery 1.9.1 / 2.0.0
- [x] add build plot size

**docs**
- [ ] add FAQs; async / sync, browser support, dependencies
- [ ] add quick migration guide from v3.x to v4.x
- [x] add links to older documentation

Things looking likely to get bumped until 4.2.0:
- [ ] reimplement icon support
- [ ] add left/right arrow support for button focus (#137)
- [ ] set default locale based on html lang attribute
- [ ] allow user to specify which button has focus in options argument
- [ ] allow hoisting of `ok`, `cancel` and `confirm` button declarations up to root level options object on wrapper methods
