### ISSUE TITLE
Bootbox 4.2.0 (next minor release) task list

### ISSUE THREAD

**Issue by makeusabrew** [makeusabrew/bootbox#162]
**core**
- [ ] reimplement icon support
- [ ] add left/right arrow support for button focus (#137)
- [ ] set default locale based on html lang attribute
- [ ] allow user to specify which button has focus in options argument
- [ ] allow hoisting of `ok`, `cancel` and `confirm` button declarations up to root level options object on wrapper methods
- [ ] add official support for radio button options in prompt (#189)
- [ ] allow `width` and `height` options (#190)

**docs**
- [ ] add FAQs; async / sync, browser support, dependencies
- [ ] add quick migration guide from v3.x to v4.x

**Comment by kriskd** [comment]
> Being able to define an ID would be nice, so that I can reference it later. I came across this need when wanting the alert to fade out 1.5 seconds after showing it.

> Putting this code at line 540 works in v4.1.0:
> if(options.id !== undefined){
> dialog.attr("id", options.id);
> }

I looked through the project and I don't believe this was added.  This would be useful to me, any chance of getting it in?  Do you need a PR?
