### ISSUE TITLE
Bootbox 4.3.0 (next minor release) task list

### ISSUE THREAD

**Issue by makeusabrew** [makeusabrew/bootbox#220]
**core**
- [ ] reimplement icon support
- [ ] add left/right arrow support for button focus (#137)
- [ ] set default locale based on html lang attribute
- [ ] allow user to specify which button has focus in options argument
- [ ] allow hoisting of `ok`, `cancel` and `confirm` button declarations up to root level options object on wrapper methods
- [ ] add official support for radio button options in prompt (#189)
- [ ] allow `width` and `height` options (#190)
- [x] allow Bootstrap 3.1 `size` parameter to be specified (#228)

**docs**
- [ ] add FAQs; async / sync, browser support, dependencies
- [ ] add quick migration guide from v3.x to v4.x
